# Generated by Django 5.1.6 on 2025-09-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='chain_id',
            field=models.PositiveIntegerField(default=-1),
        ),
    ]
