# Generated by Django 5.1.6 on 2025-12-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_chain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='chain_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
