# Generated by Django 5.1.6 on 2025-04-11 14:28

import helpers.validators.DidLengthValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=255, unique=True, validators=[helpers.validators.DidLengthValidator.DidLengthValidator(max_length=71, min_length=71)])),
                ('type', models.CharField(choices=[('D', 'Dataset'), ('A', 'Algorithm')], default='D', max_length=1)),
            ],
            options={
                'db_table': 'asset',
            },
        ),
    ]
