# Generated by Django 5.1.6 on 2025-04-11 14:28

import bitfield.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('D', 'Denied'), ('R', 'Resolved')], max_length=1)),
                ('permitted', bitfield.models.BitField((('trusted_algorithm_publisher', 'Trusted Algorithm Publisher'), ('trusted_algorithm', 'Trusted Algorithm'), ('trusted_credential_address', 'Trusted Credential Address'), ('allow_network_access', 'Allow Network Access')), default=None)),
                ('last_updated_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'consent responses',
                'db_table': 'consent_response',
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('request', bitfield.models.BitField((('trusted_algorithm_publisher', 'Trusted Algorithm Publisher'), ('trusted_algorithm', 'Trusted Algorithm'), ('trusted_credential_address', 'Trusted Credential Address'), ('allow_network_access', 'Allow Network Access')), default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_consents', to='assets.asset')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_consents', to='assets.asset')),
            ],
            options={
                'db_table': 'consent',
            },
        ),
    ]
