# Generated by Django 5.1.6 on 2025-02-24 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consent',
            name='solicitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_consents', to=settings.AUTH_USER_MODEL),
        ),
    ]
