# Generated by Django 5.1.6 on 2025-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentresponse',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('D', 'Denied'), ('R', 'Resolved')], default='P', max_length=1),
        ),
    ]
