# Generated by Django 5.1.6 on 2025-05-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0003_alter_consentresponse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
