# Generated by Django 5.1.6 on 2025-09-18 10:24

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0004_alter_consent_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='request',
            field=bitfield.models.BitField((('trusted_algorithm_publisher', 'Trusted Algorithm Publisher'), ('trusted_algorithm', 'Trusted Algorithm'), ('allow_network_access', 'Allow Network Access')), default=None),
        ),
        migrations.AlterField(
            model_name='consentresponse',
            name='permitted',
            field=bitfield.models.BitField((('trusted_algorithm_publisher', 'Trusted Algorithm Publisher'), ('trusted_algorithm', 'Trusted Algorithm'), ('allow_network_access', 'Allow Network Access')), default=None),
        ),
    ]
