# Generated by Django 5.1.6 on 2025-02-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_did', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('state', models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('I', 'Inactive'), ('R', 'Rejected'), ('D', 'Deleted')], default='P', max_length=1)),
            ],
            options={
                'db_table': 'consent',
            },
        ),
    ]
