# Generated by Django 5.1.6 on 2025-02-28 15:21

import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consent',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_consents', to='consents.asset'),
        ),
        migrations.AddField(
            model_name='consent',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_consents', to='consents.asset'),
        ),
        migrations.AddField(
            model_name='consenthistory',
            name='consent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='consents.consent'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['did', 'owner'], name='asset_did_47f895_idx'),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('algorithm', 'dataset'), name='unique_algorithm_dataset'),
        ),
    ]
