# Generated by Django 5.1.6 on 2025-04-09 14:00

import django.db.models.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='solicitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consentresponse',
            name='consent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='consents.consent'),
        ),
        migrations.AddConstraint(
            model_name='consent',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['IMMEDIATE'], fields=('algorithm', 'dataset'), name='unique_algorithm_dataset'),
        ),
    ]
