# Generated by Django 5.1.6 on 2025-04-01 11:14

import consents.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='did',
            field=models.CharField(max_length=255, unique=True, validators=[consents.validators.DidLengthValidator(max_length=71, min_length=71)]),
        ),
        migrations.AlterField(
            model_name='consent',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_consents', to='consents.asset', validators=[consents.validators.DidLengthValidator(max_length=71, min_length=71)]),
        ),
        migrations.AlterField(
            model_name='consent',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_consents', to='consents.asset', validators=[consents.validators.DidLengthValidator(max_length=71, min_length=71)]),
        ),
    ]
