# Generated by Django 5.1.6 on 2025-04-09 14:08

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentresponse',
            name='permitted',
            field=bitfield.models.BitField((('trusted_algorithm_publisher', 'Trusted algorithm publisher'), ('trusted_algorithm', 'Trusted algorithm'), ('trusted_credential_address', 'Trusted credential address')), default=None),
        ),
    ]
