# Generated by Django 5.1.6 on 2025-04-09 15:09

import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0003_consentresponse_permitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='request',
            field=bitfield.models.BitField((('trusted_algorithm_publisher', 'Trusted algorithm publisher'), ('trusted_algorithm', 'Trusted algorithm'), ('trusted_credential_address', 'Trusted credential address'), ('allow_network_access', 'Allow network access')), default=None),
        ),
        migrations.AlterField(
            model_name='consentresponse',
            name='permitted',
            field=bitfield.models.BitField((('trusted_algorithm_publisher', 'Trusted algorithm publisher'), ('trusted_algorithm', 'Trusted algorithm'), ('trusted_credential_address', 'Trusted credential address'), ('allow_network_access', 'Allow network access')), default=None),
        ),
        migrations.AlterField(
            model_name='consentresponse',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('D', 'Denied'), ('R', 'Resolved')], max_length=1),
        ),
    ]
