# Generated by Django 5.1.6 on 2025-02-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0003_consent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='state',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected'), ('D', 'Deleted')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='consenthistory',
            name='state',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected'), ('D', 'Deleted')], max_length=1),
        ),
    ]
