# Generated by Django 5.1.6 on 2025-02-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0004_alter_consent_state_alter_consenthistory_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consenthistory',
            old_name='state',
            new_name='from_state',
        ),
    ]
