# Generated by Django 5.1.6 on 2025-04-10 15:21

import bitfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0004_alter_consent_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consent',
            name='request',
            field=bitfield.models.BitField(('trusted_algorithm_publisher', 'trusted_algorithm', 'trusted_credential_address', 'allow_network_access'), default=None),
        ),
        migrations.AlterField(
            model_name='consentresponse',
            name='permitted',
            field=bitfield.models.BitField(('trusted_algorithm_publisher', 'trusted_algorithm', 'trusted_credential_address', 'allow_network_access'), default=None),
        ),
    ]
