# Generated by Django 5.1.6 on 2025-02-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0005_rename_state_consenthistory_from_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consenthistory',
            old_name='from_state',
            new_name='state',
        ),
    ]
