"""empty message.

Revision ID: 43a6b430497a
Revises: 1d94d2aa3b99
Create Date: 2025-02-19 12:44:36.310948

"""



# revision identifiers, used by Alembic.
revision = "43a6b430497a"
down_revision = "1d94d2aa3b99"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
