"""empty message.

Revision ID: 1d94d2aa3b99
Revises: 82ec1c1a2b8c
Create Date: 2025-02-19 11:46:13.750048

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1d94d2aa3b99"
down_revision = "82ec1c1a2b8c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consent", sa.Column("asset_owner", sa.String(length=80), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("consent", "asset_owner")
    # ### end Alembic commands ###
