"""empty message.

Revision ID: 4761b469abef
Revises: 43a6b430497a
Create Date: 2025-02-21 12:00:13.973792

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4761b469abef"
down_revision = "43a6b430497a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consent", sa.Column("solicitor_public_key", sa.String(), nullable=False),
    )
    op.add_column("consent", sa.Column("owner_public_key", sa.String(), nullable=False))
    op.drop_constraint("consent_user_public_key_fkey", "consent", type_="foreignkey")
    op.create_foreign_key(None, "consent", "user", ["owner_public_key"], ["public_key"])
    op.create_foreign_key(
        None, "consent", "user", ["solicitor_public_key"], ["public_key"],
    )
    op.drop_column("consent", "user_public_key")
    op.drop_column("consent", "asset_owner")
    op.drop_column("consent", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "consent", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "consent",
        sa.Column(
            "asset_owner", sa.VARCHAR(length=80), autoincrement=False, nullable=False,
        ),
    )
    op.add_column(
        "consent",
        sa.Column("user_public_key", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "consent", type_="foreignkey")
    op.drop_constraint(None, "consent", type_="foreignkey")
    op.create_foreign_key(
        "consent_user_public_key_fkey",
        "consent",
        "user",
        ["user_public_key"],
        ["public_key"],
    )
    op.drop_column("consent", "owner_public_key")
    op.drop_column("consent", "solicitor_public_key")
    # ### end Alembic commands ###
