"""empty message.

Revision ID: 82ec1c1a2b8c
Revises: 2b7380507a71
Create Date: 2025-02-18 12:49:59.016208

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "82ec1c1a2b8c"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("public_key", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("public_key"),
    )
    op.create_table(
        "consent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("asset_did", sa.String(length=80), nullable=False),
        sa.Column("reason", sa.String(length=600), nullable=False),
        sa.Column(
            "state",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="consentstate"),
            nullable=False,
        ),
        sa.Column("user_public_key", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_public_key"],
            ["user.public_key"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("dummy_model")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy_model",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="dummy_model_pkey"),
    )
    op.drop_table("consent")
    op.drop_table("user")
    # ### end Alembic commands ###
