# Generated by Django 5.1.6 on 2025-09-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_consentsuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=255, unique=True)),
                ('nonce', models.CharField(max_length=255)),
                ('chain_id', models.PositiveIntegerField(default=1)),
                ('domain', models.CharField(max_length=255)),
                ('uri', models.TextField()),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'wallet_nonces',
                'indexes': [models.Index(fields=['expires_at'], name='wallet_nonc_expires_5cec92_idx')],
            },
        ),
    ]
