# Generated by Django 5.1.6 on 2025-02-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consentsuser',
            options={},
        ),
        migrations.AddField(
            model_name='consentsuser',
            name='address',
            field=models.CharField(default='-', max_length=80, unique=True),
        ),
        migrations.AlterModelTable(
            name='consentsuser',
            table='users',
        ),
    ]
