# Generated by Django 5.1.6 on 2025-04-25 08:46

import django.contrib.auth.models
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_consentsuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='consentsuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('helper', users.models.ConsentsUserManager()),
            ],
        ),
    ]
